### ISSUE TITLE
ada pembaharuan dari gojek

### ISSUE THREAD

**Issue by hasbi204** [decoderid/gojek-api-php-native#10]
Seperti nya ada update dari gojek nya om soalnya tidak bisa request OTP, mendapat response seperti ini:

Gagal Mengirim OTP : {"errors":[{"message":"Nikmati yang terbaik dari Gojek pada versi terbaru. Memperbarui sekarang.","message_severity":"error","code":"goid:error:ratelimited:device","message_title":"Oh, aplikasi ini perlu pembaruan cepat"}],"success":false}

**Comment by ariel3131** [comment]
udah utak atik blm nemu enkripsianya pakai apa trus key nya darimana. moga ada yg bisa bantu

**Comment by decoderid** [comment]
Cek Ini:

https://github.com/decoderid/gojek-api-php-native/issues/11#issuecomment-2379897157
