### ISSUE TITLE
Login error = Oops, something's wrong

### ISSUE THREAD

**Issue by ariel3131** [decoderid/gojek-api-php-native#11]
ada pembaruan diversi 4.85.1 keatas
bagian header ada variable baru yaitu "signature" , kalau data "signature" nya tidak valid respon servernya http 400 atau "Oops, something's wrong" udah utak atik sana sini blum nemu enkripsianya. barangkali ada yang bisa bantu
![Screenshot_20240927-222415929~2](https://github.com/user-attachments/assets/cd777657-dc0f-449b-99e3-b7da8da437ae)

**Comment by decoderid** [comment]
Hasil Testing Header:

#### Fingerprint
57:50:4F:97:C4:D2:FC:41:93:09:3B:74:5E:6F:56:AC:9E:1A:B2:05:4B:56:23:59:45:50:80:E2:C7:EB:E7:EF

#### Metadata
1:UNKNOWN,2:UNKNOWN,3:1635930927140-8060886151656134872,4:113378,5:mt6768|1700|8,6:92:01:D2:9C:53:44,7:<unknown ssid>,8:720x1478,9:,10:1,11:uumyufckJFZbLI44CNQp0QtkgEoDmLoCnizwncy5PBU=,12:VKEY_DISABLED,13:1003,14:1727463074,16:0,17:1

#### Signature
36e47e258609787d7ab2a53ca8b5b4967c63fd8e99e7f8b906a0e6370291e2ab:d89e9a3b693d12eabef5fadbcac658b5d63765a422896f84f4fdada80d50261eb84223217c00000060180f847c000000501923217c00000060040f847c0000006163fbfed06925dfe50fd3ea7da0f403:N:1727463074193

#### Decompiler
![{959010C5-DA23-4409-A8A7-70805CDBDF65}](https://github.com/user-attachments/assets/1abdd039-f878-4be8-bd6f-6dd035d27f05)

**Comment by ariel3131** [comment]
itu enkripsinya pakai metode apa bang? ada key nya gak?

**Comment by ariel3131** [comment]
itu enkripsinya pakai metode apa bang? ada key nya gak?
