### ISSUE TITLE
Hasil Testing Header:

### ISSUE THREAD

**Issue by ariel3131** [decoderid/gojek-api-php-native#12]
Hasil Testing Header:

#### Fingerprint
57:50:4F:97:C4:D2:FC:41:93:09:3B:74:5E:6F:56:AC:9E:1A:B2:05:4B:56:23:59:45:50:80:E2:C7:EB:E7:EF

#### Metadata
1:UNKNOWN,2:UNKNOWN,3:1635930927140-8060886151656134872,4:113378,5:mt6768|1700|8,6:92:01:D2:9C:53:44,7:<unknown ssid>,8:720x1478,9:,10:1,11:uumyufckJFZbLI44CNQp0QtkgEoDmLoCnizwncy5PBU=,12:VKEY_DISABLED,13:1003,14:1727463074,16:0,17:1

#### Signature
36e47e258609787d7ab2a53ca8b5b4967c63fd8e99e7f8b906a0e6370291e2ab:d89e9a3b693d12eabef5fadbcac658b5d63765a422896f84f4fdada80d50261eb84223217c00000060180f847c000000501923217c00000060040f847c0000006163fbfed06925dfe50fd3ea7da0f403:N:1727463074193

#### Decompiler
![{959010C5-DA23-4409-A8A7-70805CDBDF65}](https://github.com/user-attachments/assets/1abdd039-f878-4be8-bd6f-6dd035d27f05)

_Originally posted by @decoderid in https://github.com/decoderid/gojek-api-php-native/issues/11#issuecomment-2379897157_

**Comment by ariel3131** [comment]
yg abang kirim gambar itu aku cek buat header "x-m1" nya kayaknya bang, yang aku maksud metode enkripsianya yang header signature nya bang. terimakasih banyak bang

**Comment by decoderid** [comment]
> yg abang kirim gambar itu aku cek buat header "x-m1" nya kayaknya bang, yang aku maksud metode enkripsianya yang header signature nya bang. terimakasih banyak bang

X-M1 = Signature

**Comment by ariel3131** [comment]
ouh , terimakasih bang.. tp buat metode enkripsianya gmn bang? pakai metode enkripsi apa?

**Comment by ariel3131** [comment]
bantuanya bang, terimakasih

**Comment by ariel3131** [comment]
udah bisa bang? @decoderid
