### ISSUE TITLE
Darimana cara mendapat payment id saat mau membayar qris dinamis?

### ISSUE THREAD

**Issue by bagusok** [decoderid/gojek-api-php-native#3]
Darimana cara mendapat payment id saat mau membayar qris dinamis?

**Comment by bagusok** [comment]
fix in #4

**Comment by decoderid** [comment]
gunakan ini **validateQRCode** dia akan muncul **paymentId** kalo **Dynamic**

**Comment by bagusok** [comment]
Kosong bro, lu coba aja, harus createpayment dulu

**Comment by decoderid** [comment]
> Kosong bro, lu coba aja, harus createpayment dulu

gw blm coba lagi, cuma prosesnya dia harus validate dulu, entah ada update kah dari sisi endpoin?

**Comment by bagusok** [comment]
Gatau, gw masukin tu endpoint yg v1 bisa

**Comment by decoderid** [comment]
solved #5
