### ISSUE TITLE
error login

### ISSUE THREAD

**Issue by kusanagi1337** [decoderid/gojek-api-php-native#6]
stdClass Object ( [data] => [success] => [errors] => Array ( [0] => stdClass Object ( [code] => goid:error:unauthorized [message] => Please update to the latest official app version and try to login again. [message_title] => Unauthorized ) ) )

dapat gini pas mau login

**Comment by decoderid** [comment]
> stdClass Object ( [data] => [success] => [errors] => Array ( [0] => stdClass Object ( [code] => goid:error:unauthorized [message] => Please update to the latest official app version and try to login again. [message_title] => Unauthorized ) ) )
> 
> dapat gini pas mau login

silahkan coba lewat demo, harusnya tidak ada masalah.

**Comment by kusanagi1337** [comment]
demo aman tapi pas coba sendiri error gitu, padahal sudah sesuai cara installnya

**Comment by kusanagi1337** [comment]
udah bisa login tapi sekarang  session revoked pas mau dipakai
