### ISSUE TITLE
request fitur add trusted device

### ISSUE THREAD

**Issue by yuyun817** [decoderid/gojek-api-php-native#8]
Salam

.![Screenshot_20240310_024551](https://github.com/decoderid/gojek-api-php-native/assets/162835591/90e4417b-5fc7-4ef0-9094-2c1adc8fadda)

seperti pada gambar tersebut
apa bisa di tambah fungsi buat add sbg trusted device?

supaya misal di hp login
pas mau login di api ga perlu otp lagi

**Comment by decoderid** [comment]
bisa coba ini

https://github.com/decoderid/gojek-api-php-native/blob/2e8ceaed624d43ee54a6598ee7c2515fd567c203/src/GojekApi.php#L87
