### ISSUE TITLE
TOPUP

### ISSUE THREAD

**Issue by d-jumper** [decoderid/gojek-api-php-native#9]
Hi,
sebelumnya terima kasih atas library nya, ini sangat bagus, sangat membantu dan bekerja diserver saya.

Tidak ada yang salah dengan library ini, dan sangat mudah dioperasikan. Tapi saya mempunyai satu keinginan, yaitu bisakah tolong berikan fitur TOPUP ONEKLIK B*A?
ya, saya sangat butuh fitu itu, terima kasih:)

**Comment by Obelix1337** [comment]
bisa aja sih
